### ISSUE TITLE
Decoder discards additional co-ordinates

### ISSUE THREAD

**Issue by lukeredpath** [rgeo/rgeo-geojson#2]
Given the Point:

```json
{
    "type": "Point",
    "coordinates": [102.0, 0.0, 0.0, "2011-03-29T08:38:50Z", 3.54, 39.80]
}
```

Where indices 0, 1, and 2 represent x, y and z co-ordinates and indices 3, 4 and 5 represent custom metadata about a point (in this case, timestamp, speed and bearing), rgeo-geojson discards the additional elements of the co-ordinates array. This is not expected behaviour.

According to the GeoJSON spec, additional elements are perfectly acceptable (emphasis mine):

> A position is represented by an array of numbers. There must be at least two elements, and may be more. The order of elements must follow x, y, z order (easting, northing, altitude for coordinates in a projected coordinate reference system, or longitude, latitude, altitude for coordinates in a geographic coordinate reference system). **Any number of additional elements are allowed** -- interpretation and meaning of additional elements is beyond the scope of this specification.

**Comment by teeparham** [comment]
Closing as stale / will not fix. Use properties if you have additional coordinate information. Use `m` and `z` if you have those.
