### ISSUE TITLE
Minor error in entities.rb: misspelling of object_id

### ISSUE THREAD

**Issue by ijdickinson** [rgeo/rgeo-geojson#21]
In `lib/rgeo/geo_json/entities.rb`, lines 26ff

    def inspect # :nodoc:
        "#<#{self.class}:0x#{objectid.to_s(16)} id=#{@id.inspect} geom=#{@geometry ? @geometry.as_text.inspect : 'nil'}>"
    end

`objectid.to_s` should read `object_id.to_s`

**Comment by teeparham** [comment]
Thanks for reporting this bug.
