### ISSUE TITLE
encode lat/long ordering

### ISSUE THREAD

**Issue by piotr-galas** [rgeo/rgeo-geojson#35]
I defined my polygon using RGeo::Geographic.simple_mercator_factory

```ruby
factory = RGeo::Geographic.simple_mercator_factory

bronowice = factory.point(50.078936, 19.877016)
bienczyce = factory.point(50.083266, 20.029741)
debniki = factory.point(50.011346, 19.869917)
biezanow = factory.point(50.011099, 20.035068)
line = factory.line_string([bronowice, bienczyce, biezanow, debniki])
area = factory.polygon(line)
```

When I tried to encode polygon I get wrong order of long/lat ( geoJson should reverse lat/long )and also it is unnnecessary nested array in :coordinates

```ruby
{"type"=>"Polygon", "coordinates"=>[[[50.078936, 19.877016], [50.083266, 20.029741], [50.011099, 20.035068], [50.011346, 19.869917], [50.078936, 19.877016]]]}
```

**Comment by apprentice1988** [comment]
Have you solved this issue? geojson point is [lat, lng] while wkt point is [lng, lat], so the order is reverse. I think it's better to add config to this gem to decide which order being used.

**Comment by piotr-galas** [comment]
Regards to unnecessary nested array, I was wrong. It is necessary because we can have multiple poligons. 

Regards order I just implement reverse logic in  my model
`area` is name of field in database

```ruby
  def json_area
    return unless area
    json_area = RGeo::GeoJSON.encode(area)
    json_area['coordinates'].first.map(&:reverse!)
    json_area
  end
``` 

I am not sure that `config` is the best place for it. I prefer to add `order` option to `encode`  method. 

```ruby
 RGeo::GeoJSON.encode(area, order:  :lat_lng)
 RGeo::GeoJSON.encode(area, order:  :lng_lat)
```

@apprentice1988 do you think that name of option is ok?

**Comment by BuonOmo** [comment]
@piotr-galas do you still have an issue ? 

I'm really not found of the order option myself. I think we should just set the correct one in the first place.

Another issues in your example is that your polygon is not closed. Factories could return `nil` because this is an illegal polygon.

**Comment by piotr-galas** [comment]
@BuonOmo  I am no longer working on a project where use this gem.

**Comment by BuonOmo** [comment]
@piotr-galas ok sorry for the inconvenience, we'll still fix that one since order matters here and this looks like a huge bug to me.
