### ISSUE TITLE
No Lib folder

### ISSUE THREAD

**Issue by Tioneb12** [rgeo/rgeo-geojson#41]
I installed the gem but I do not have a lib/rgeo/... folder. Is this normal? Do I have to create this folder manually?

**Comment by teeparham** [comment]
Gem files are installed normally. You don't need to do anything special in your project. After you install the gem, you can require it with `require 'rgeo-geojson'`.

```sh
$ gem install rgeo-geojson
$ irb
> require 'rgeo-geojson'
=> true
> RGeo::GeoJSON
=> RGeo::GeoJSON
```

**Comment by pedros007** [comment]
@Tioneb12 check out this [set of articles to learn more about how to use RGeo](http://daniel-azuma.com/articles/georails/). The examples in the [README.md](https://github.com/rgeo/rgeo-geojson/blob/master/README.md) also shows some simple encode/decode of features.  Another useful resource when learning a library such as rgeo-geojson is the [unit tests](https://github.com/rgeo/rgeo-geojson/blob/master/test/basic_test.rb).  For example, here's [one way to work with a feature collection](https://github.com/rgeo/rgeo-geojson/blob/master/test/basic_test.rb#L218-L252).
