### ISSUE TITLE
Encode PostGIS compatible Polygon

### ISSUE THREAD

**Issue by sepowitz** [rgeo/rgeo-geojson#44]
Thanks for the great lib. For the most part it has been a breeze to use. I am however coming across a bit of an issue when attempting to encode a Geometry value to geoJson.

```
'POLYGON ((-73.79113930812991 42.208615924064496, -73.79113930812991 42.20864290367541, -73.79110288382999 42.20864290367541, -73.79110288382999 42.208615924064496, -73.79113930812991 42.208615924064496))'
```

When attempting to encode the value above using `RGeo::GeoJSON.encode` I get nil

Any help would be greatly appreciated!

**Comment by BuonOmo** [comment]
Hi @sepowitz,

The `encode` is made to work with `RGeo` objects:

https://github.com/rgeo/rgeo-geojson/blob/7316c9642c601c9d8f8070acd4ef62452a7eb029/lib/rgeo/geo_json/coder.rb#L113-L153

However I get it that this is unclear for one who is new to the library, and we should document it properly.

Here's how to parse the polygon you gave:

```ruby
require 'rgeo'
require 'rgeo/geo_json'
require 'json' # only for Kernel#jj

poly = 'POLYGON ((-73.79113930812991 42.208615924064496, -73.79113930812991 42.20864290367541, -73.79110288382999 42.20864290367541, -73.79110288382999 42.208615924064496, -73.79113930812991 42.208615924064496))'

parsed_hash = RGeo::GeoJSON.encode RGeo::Cartesian.factory.parse_wkt poly

jj parsed_hash
```
