### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by harto** [rgeo/rgeo-geojson#61]
Hi there, thanks for your work on this project.
I was wondering if it would be possible to cut a new minor version release?
It looks like a bunch of useful stuff was added since the last release in 2018 (especially of interest to me is https://github.com/rgeo/rgeo-geojson/pull/56).

**Comment by BuonOmo** [comment]
It seems reasonable to me. To be honest I don't remember what were the reasons why we didn't go further on this. Maybe @keithdoggett you have an idea ?

I see that the open PRs could be closed quite fast. It seems to me like a few hours of work to be sure about ourselves and publish. I don't have those now, More likely in september/october...

**Comment by keithdoggett** [comment]
@BuonOmo I think we may have thought we'd have more changes and never made a release then forgot to do it. I can do a round of reviews and a release on Sunday.

**Comment by keithdoggett** [comment]
@harto @BuonOmo released v2.2.0 with the pending batch of changes

**Comment by harto** [comment]
Great! Thank you!
